
GET_HEROES="IEconDOTA2_570/GetHeroes/v0001/"
BASE="https://api.steampowered.com/"
GET_MATCH_HISTORY = "IDOTA2Match_570/GetMatchHistory/v001/"
GET_MATCH_HISTORY_BY_SEQ_NUM = "IDOTA2Match_570/GetMatchHistoryBySequenceNum/v0001/"
GET_MATCH_DETAILS = "IDOTA2Match_570/GetMatchDetails/v001/"
GET_LEAGUE_LISTING = "IDOTA2Match_570/GetLeagueListing/v0001/"
GET_LIVE_LEAGUE_GAMES = "IDOTA2Match_570/GetLiveLeagueGames/v0001/"
GET_TEAM_INFO_BY_TEAM_ID = "IDOTA2Match_570/GetTeamInfoByTeamID/v001/"
GET_PLAYER_SUMMARIES = "ISteamUser/GetPlayerSummaries/v0002/"
GET_GAME_ITEMS = "IEconDOTA2_570/GetGameItems/v1/"
GET_TOURNAMENT_PRIZE_POOL = "IEconDOTA2_570/GetTournamentPrizePool/v1/"
GET_TOP_LIVE_GAME="IDOTA2Match_570/GetTopLiveGame/v1/"
BASE_ITEMS_IMAGES_URL = 'http://cdn.dota2.com/apps/dota2/images/items/'
BASE_HERO_IMAGES_URL = 'http://cdn.dota2.com/apps/dota2/images/heroes/'
GET_SUPPORTED_API_LIST="ISteamWebAPIUtil/GetSupportedAPIList/v0001/"
STRATZ_BASE="https://api.stratz.com/graphql"
GET_PUBLIC_MATCHES="publicMatches/"
OPEN_DOTA_BASE="https://api.opendota.com/api/"
DOTA2_CONSTANTS_REPO="odota/dotaconstants/"
DOTA2_CONSTANTS_ITEMS="build/items.json"
OPEN_DOTA_MATCH='matches/'
GIT_BASE='https://api.github.com/repos/'
DOTABUFF_HEROES_DETAILED='https://raw.githubusercontent.com/dotabuff/d2vpkr/master/dota/scripts/npc/npc_heroes.txt'
DOTABUFF_HERO_ABILITY_BASE="https://raw.githubusercontent.com/dotabuff/d2vpkr/master/dota/scripts/npc/heroes/" #name +".txt"  
DOTA_ABILITIES_LANG_EN="https://raw.githubusercontent.com/dotabuff/d2vpkr/master/dota/resource/localization/abilities_english.txt"
DOTAB_HERO_LORE="https://raw.githubusercontent.com/odota/dotaconstants/refs/heads/master/build/hero_lore.json"
DOTA_ITEM_INFO="https://raw.githubusercontent.com/odota/dotaconstants/refs/heads/master/build/items.json"
DOTA_ABILITY_IDS="https://raw.githubusercontent.com/odota/dotaconstants/refs/heads/master/build/ability_ids.json"